package com.telmarket.entity;
// Generated Jul 8, 2018 3:59:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private int roleId;
     private String userName;
     private String email;
     private String password;
     private Date regDate;
     private String contactNo;
     private Set productOrders = new HashSet(0);

    public Users() {
    }

	
    public Users(int roleId, String userName, String email, String password, Date regDate, String contactNo) {
        this.roleId = roleId;
        this.userName = userName;
        this.email = email;
        this.password = password;
        this.regDate = regDate;
        this.contactNo = contactNo;
    }
    public Users(int roleId, String userName, String email, String password, Date regDate, String contactNo, Set productOrders) {
       this.roleId = roleId;
       this.userName = userName;
       this.email = email;
       this.password = password;
       this.regDate = regDate;
       this.contactNo = contactNo;
       this.productOrders = productOrders;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }




}


